[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
healthcheckPath = "/up"
healthcheckTimeout = 120
healthcheckStartPeriod = 60
